name: Close Pull Request
inputs:
  testLevel:
    description: "Deployment Apex testing level."
    type: choice
    default: RunLocalTests
    options:
      - NoTestRun
      - RunSpecifiedTests
      - RunLocalTests
      - RunAllTestsInOrg
  path:
    description: "Path to the local source files to deploy."
    type: string
    default: force-app/**
  sfUser:
    description: "The Org User"
    type: string
    required: true
  sfConsumerKey:
    description: "The Org's Github Connect App Consumer Key"
    type: string
    required: true

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: ricardo100671/salesforce_cicd/oauthdeploy@main
      with:
        dryRun: false
        testLevel: NoTestRun
        sfUser: ${{ inputs.sfUser }}
        sfConsumerKey: ${{ inputs.sfConsumerKey }}
  close_job:
    # this job will only run if the PR has been closed without being merged
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo PR #${{ github.event.number }} has been closed without being merge