name: Validate Pull Request
description: 'Validates a deployment without applying changes using SF_CONSUMER_KEY and CERT_PRIVATE_KEY stored in repository secrets.'

inputs:
  path:
    description: "Path to the local source files to deploy."
    type: string
    default: force-app/**
  sfUser:
    description: "The Org User"
    type: string
    required: true
  sfConsumerKey:   
    description: "The Org's Github Connect App Consumer Key"
    type: string
    required: true
on:
  pull_request:
      paths: ${{ inputs.path }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validating
        uses: ricardo100671/salesforce_cicd/oauthdeploy@main
        with:
          sfUser: ${{ inputs.sfUser }}
          sfConsumerKey: ${{ inputs.sfConsumerKey }}
          dryRun: true
          path: ${{ inputs.path }}