name: Close Pull Request
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
        uses: ricardo100671/salesforce_cicd/closePullRequest@main
        with:
          sfUser:
          path: force-app/**