name: Validate Pull Request

on:
  pull_request:
      paths:
      - 'force-app/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validating
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_DEVHUB_AUTHURL }}
          DRY_RUN: true